sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: H2pcuPvqVAgdb6qlhiB5NM3q7HYkySN5Z4sfMqiFh32NOvGYHEu+FeordGlSrgZIdROl4pn9lEhCrqGqMao42zUam9TEPyT4XDKV4KyAEQIcw9iITAqGj7A+74KC2+JLDEn/JaQc3JN5Pil0DYz/UBV3X2YuhFtnQHWnVXRoidu9A/xZb+9PIVkZtBiLoqq5KeOIWR1x3fQuM8ZMSxxDqaPLnKkTDS03ciQFqtXYCbhTmqsZvGxtfc5sWdSyvCZ9JmHFoqJ9i2MuQYqiq/L3czG3TqvhE0rHOmvtPExSJhfxyD8vvHe8SzXISWRgxq/hMIeQskjH43y7i7OhtGFFmSitlNX2R2X+xj6XSLEru4fxvLJ/UshIR94KaKhp0WFWUtHNNvrtwJ4UnZTVqeGdFkLO+MnoiCSrBHM4Xg7RAsDjx/yBxfYOxj9OLKAlNN0mx3dEJIa1IKuoyp1y9nVkSE9GU5in0Le5t+mzjfPm0/QQRlTeht+5KolCMuG9EkBhBXZyzR2+qPP5GZaYFCXsxA7wKXDyrs/kwm4naNOV7Ru1BxrtPFGRMimdk19N9m94cwTBSsi6xAsyETZH81XrOcSVj0t+R4Hsq/ed/UbIkthCoe605SbFDSN8bQ4gl+Rv8ce0wahsoS+pf0TX32bMJs3QbNgQ/8EO7zT9PRTxw+4=
branches:
  only:
  - master
